#ifndef KVM__KVM_FDT_H
#define KVM__KVM_FDT_H

enum phandles {
	PHANDLE_RESERVED = 0,
	PHANDLE_PLIC,
	PHANDLE_AIA_APLIC,
	PHANDLE_AIA_IMSIC,
	PHANDLE_CVM_VIRTIO_RESTRICTED_DMA,
	PHANDLE_CVM_VFIO_RESTRICTED_DMA,
	PHANDLES_MAX
};

#define PHANDLE_CPU_INTC_BASE	PHANDLES_MAX

#endif /* KVM__KVM_FDT_H */
